#!/bin/bash

# Stripe Key Setup Helper
echo "🔑 Stripe Key Setup Required"
echo "================================"
echo ""
echo "The current Stripe keys are invalid/placeholder."
echo "You need to get your real keys from Stripe Dashboard:"
echo ""
echo "1. Go to: https://dashboard.stripe.com/apikeys"
echo "2. For LOCAL DEVELOPMENT, use TEST keys:"
echo "   - Publishable key: pk_test_..."
echo "   - Secret key: sk_test_..."
echo ""
echo "3. For PRODUCTION (Vercel), use LIVE keys:"
echo "   - Publishable key: pk_live_..."
echo "   - Secret key: sk_live_..."
echo ""
echo "4. Update .env.local with your TEST keys:"
echo "   NEXT_PUBLIC_STRIPE_PUBLISHABLE_KEY=pk_test_your_key_here"
echo "   STRIPE_SECRET_KEY=sk_test_your_key_here"
echo ""
echo "5. Restart dev server: npm run dev"
echo ""
echo "Test cards you can use:"
echo "   Success: 4242 4242 4242 4242"
echo "   Decline: 4000 0000 0000 0002"
echo "   Any future expiry date and any 3-digit CVC"
