// Products API Endpoint
// Auto-generated by Product Integration Agent

const products = [
  {
    "asin": "B0D9HT7ND8",
    "title": "Organic Hydroponic Fertilizer Concentrate",
    "full_title": "Nature's Way Soil Organic Hydroponic Fertilizer Concentrate \u2013 Made Fresh Weekly-32 oz \u2013 Makes 512 Gallons of Nutrient Solution \u2013 Organic Plant Food for Hydroponic Systems, Aquaponics",
    "price": 19.99,
    "category": "Fertilizers",
    "features": [
      "Organic",
      "Concentrate"
    ],
    "product_type": "hydroponic",
    "active": true,
    "description": "Concentrated hydroponic fertilizer that provides complete nutrition for soilless growing systems."
  },
  {
    "asin": "B0DXP97C6F",
    "title": "Liquid Bone Meal Fertilizer",
    "full_title": "Nature's Way Soil Liquid Bone Meal Fertilizer \u2013 32 Ounce/1 Gallon Organic Phosphorus & Calcium for Healthy Roots, Flowers & Fruits \u2013 Fast-Absorbing Liquid Plant Food for Vegetables, Flowers, Trees",
    "price": 19.99,
    "category": "Fertilizers",
    "features": [
      "Organic",
      "Liquid",
      "Fast-Absorbing",
      "1 Gallon"
    ],
    "product_type": "bone_meal",
    "active": true,
    "description": "Premium organic fertilizer designed to nourish your plants naturally and promote healthy growth."
  },
  {
    "asin": "B0FFZPLCG7",
    "title": "Nature\u2019s Way Soil\u00ae Liquid Kelp Fertilizer",
    "full_title": "Nature\u2019s Way Soil\u00ae Liquid Kelp Fertilizer \u2013 Organic Seaweed Plant Food for Lawn, Garden, Flowers & Vegetables | Cold-Processed | Natural Growth Booster & Soil Revitalizer (32 Ounce)",
    "price": 19.99,
    "category": "Fertilizers",
    "features": [
      "Organic",
      "Liquid",
      "Liquid Formula"
    ],
    "product_type": "seaweed_fertilizer",
    "active": true,
    "description": "Natural seaweed extract that provides trace minerals and growth hormones for enhanced plant vigor."
  },
  {
    "asin": "B0FGWSKGCY",
    "title": "Seaweed & Humic Acid Lawn Treatment",
    "full_title": "Nature's Way Soil\u00ae Seaweed & Humic Acid Lawn Treatment \u2013 32 oz Concentrate | Liquid Soil Revitalizer with 4.5% Humic + 4.5% Cold-Processed Kelp | Organic Garden & Grass Fertilizer Additive",
    "price": 19.99,
    "category": "Fertilizers",
    "features": [
      "Organic",
      "Concentrate",
      "Liquid",
      "Liquid Formula"
    ],
    "product_type": "seaweed_fertilizer",
    "active": true,
    "description": "Natural seaweed extract that provides trace minerals and growth hormones for enhanced plant vigor."
  },
  {
    "asin": "B0822RH5L3",
    "title": "Organic Liquid Fertilizer for Garden and House Plants/100% Ogranic/USDA Certifie...",
    "full_title": "Nature's Way Soil Organic Liquid Fertilizer for Garden and House Plants/100% Ogranic/USDA Certified Biobased Product/with B-1 Vitamin, Aloe Vera Juice to Improve Transplants/Made Fresh Weekly/",
    "price": 20.99,
    "category": "Fertilizers",
    "features": [
      "Organic",
      "Liquid",
      "USDA Certified",
      "Aloe Vera"
    ],
    "product_type": "general",
    "active": true,
    "description": "Premium organic fertilizer designed to nourish your plants naturally and promote healthy growth."
  },
  {
    "asin": "B0D6886G54",
    "title": "Organic Tomato Liquid Fertilizer",
    "full_title": "Nature's Way Soil Organic Tomato Liquid Fertilizer \u2013 Made Fresh Weekly- Concentrate/Includes Vitamin B-1 and Aloe Vera for Faster Root Establishment, Healthier Transplants/Stops Blossom End Rot,",
    "price": 29.99,
    "category": "Fertilizers",
    "features": [
      "Organic",
      "Concentrate",
      "Liquid",
      "B-1 Vitamin"
    ],
    "product_type": "tomato_fertilizer",
    "active": true,
    "description": "Specialized fertilizer formulated specifically for tomatoes, preventing blossom end rot and promoting healthy fruit development."
  },
  {
    "asin": "B0F8R45FJ2",
    "title": "Nature\u2019s Way Soil\u00ae Liquid Kelp Fertilizer",
    "full_title": "Nature\u2019s Way Soil\u00ae Liquid Kelp Fertilizer \u2013 1 Gallon/Makes 1890 Gallons | Organic Seaweed Plant Food for Lawn, Garden, Flowers & Vegetables | Cold-Processed | Natural Growth Booster & Soil Revitalizer",
    "price": 34.99,
    "category": "Fertilizers",
    "features": [
      "Organic",
      "Liquid",
      "1 Gallon"
    ],
    "product_type": "seaweed_fertilizer",
    "active": true,
    "description": "Natural seaweed extract that provides trace minerals and growth hormones for enhanced plant vigor."
  },
  {
    "asin": "B0DJ1MF2BP",
    "title": "Hay and Pasture Liquid Fertilizer",
    "full_title": "Nature's Way Soil Hay and Pasture Liquid Fertilizer \u2013 Organic, Non-Toxic, Safe for Horses, Livestock \u2013 Promotes Healthy Growth, Nutrient-Rich Forage, and Enhanced Pasture Quality (1 Gallon)",
    "price": 39.99,
    "category": "Fertilizers",
    "features": [
      "Organic",
      "Liquid",
      "1 Gallon"
    ],
    "product_type": "general",
    "active": true,
    "description": "Premium organic fertilizer designed to nourish your plants naturally and promote healthy growth."
  },
  {
    "asin": "B0F9W6R4K9",
    "title": "Liquid Bone Meal Fertilizer",
    "full_title": "Nature's Way Soil Liquid Bone Meal Fertilizer \u2013 Organic Phosphorus & Calcium for Healthy Roots, Flowers & Fruits \u2013 Fast-Absorbing Liquid Plant Food for Vegetables, Flowers, Trees, and Shrubs 1 Gallon",
    "price": 39.99,
    "category": "Fertilizers",
    "features": [
      "Organic",
      "Liquid",
      "Fast-Absorbing",
      "1 Gallon"
    ],
    "product_type": "bone_meal",
    "active": true,
    "description": "Premium organic fertilizer designed to nourish your plants naturally and promote healthy growth."
  },
  {
    "asin": "B0F9B4Q5Z8",
    "title": "Nature\u2019s Way Soil\u00ae Liquid Kelp Fertilizer",
    "full_title": "Nature\u2019s Way Soil\u00ae Liquid Kelp Fertilizer \u20132.5 Gallon/Organic Seaweed Plant Food for Lawn, Garden, Flowers & Vegetables/Concentrate | Cold-Processed | Natural Growth Booster & Soil Revitalizer",
    "price": 64.99,
    "category": "Fertilizers",
    "features": [
      "Organic",
      "Concentrate",
      "Liquid",
      "2.5 Gallon"
    ],
    "product_type": "seaweed_fertilizer",
    "active": true,
    "description": "Natural seaweed extract that provides trace minerals and growth hormones for enhanced plant vigor."
  },
  {
    "asin": "B0DFV4YZ61",
    "title": "Nature\u2019s Way Soil Hay, Pasture & Lawn Fertilizer",
    "full_title": "Nature\u2019s Way Soil Hay, Pasture & Lawn Fertilizer \u2013 1 & 2.5 Gallon Organic Liquid Soil Conditioner for Grass, Turf & Forage | Pet-Safe | Microbial Nitrogen Blend | 2.5 Gallons",
    "price": 99.99,
    "category": "Fertilizers",
    "features": [
      "Organic",
      "Liquid",
      "Pet-Safe",
      "2.5 Gallon"
    ],
    "product_type": "lawn_care",
    "active": true,
    "description": "Premium organic fertilizer designed to nourish your plants naturally and promote healthy growth."
  },
  {
    "asin": "B0FFZRM6BD",
    "title": "Nature\u2019s Way Soil\u00ae Liquid Humic & Fulvic Acid",
    "full_title": "Nature\u2019s Way Soil\u00ae Liquid Humic & Fulvic Acid \u2013 32 oz Soil Conditioner with Organic Kelp \u2013 Boosts Root Growth, Water Retention & Microbial Activity \u2013 Natural Lawn & Garden Supplement \u2013 Pet-Safe",
    "price": 19.99,
    "category": "Soil & Growing Media",
    "features": [
      "Organic",
      "Liquid",
      "Pet-Safe",
      "Liquid Formula"
    ],
    "product_type": "seaweed_fertilizer",
    "active": true,
    "description": "Natural seaweed extract that provides trace minerals and growth hormones for enhanced plant vigor."
  },
  {
    "asin": "B0D52CQNGN",
    "title": "Generic Horlticural Activated Charcoal for Plants, 4 Quarts, Indoor and Outdoor,...",
    "full_title": "Generic Horlticural Activated Charcoal for Plants, 4 Quarts, Indoor and Outdoor, Charcoal for Terrariums, Conditioning for Bonsai Soil and Catus Soil, Black, NWS-4q-ABC",
    "price": 29.99,
    "category": "Soil & Growing Media",
    "features": [
      "Quart Size"
    ],
    "product_type": "charcoal",
    "active": true,
    "description": "High-quality growing medium crafted for optimal plant health and root development."
  },
  {
    "asin": "B0D69LNC5T",
    "title": "Booster and Loosener",
    "full_title": "Nature's Way Soil Booster and Loosener \u2013 Organic Formula to Enhance Soil Health, Improve Aeration, and Promote Root Growth \u2013 Ideal for Gardens, Lawns, and Potted Plants",
    "price": 29.99,
    "category": "Soil & Growing Media",
    "features": [
      "Organic"
    ],
    "product_type": "lawn_care",
    "active": true,
    "description": "High-quality growing medium crafted for optimal plant health and root development."
  },
  {
    "asin": "B0D7T3TLQP",
    "title": "Nature\u2019s Way Soil\u00ae Orchid & African Violet Potting Mix",
    "full_title": "Nature\u2019s Way Soil\u00ae Orchid & African Violet Potting Mix \u2013 Premium Coco Coir, Worm Castings, Activated Biochar & Perlite | Lightweight, Nutrient-Rich Indoor Plant Blend",
    "price": 29.99,
    "category": "Soil & Growing Media",
    "features": [
      "Worm Castings",
      "BioChar",
      "Coco Coir"
    ],
    "product_type": "orchid_care",
    "active": true,
    "description": "Carefully balanced formula designed for orchids and African violets, providing the specific nutrients these delicate plants need."
  },
  {
    "asin": "B0DC9CSMWS",
    "title": "Nature\u2019s Way Soil Dog Urine Neutralizer & Lawn Revitalizer",
    "full_title": "Nature\u2019s Way Soil Dog Urine Neutralizer & Lawn Revitalizer \u2013 32 oz/ 1 Gallon | Now with Enzymes/Pet-Safe Grass Repair Spray for Yellow Spots | Odor Eliminator & Soil Reviver for Healthy Green Lawns",
    "price": 29.99,
    "category": "Soil & Growing Media",
    "features": [
      "Pet-Safe",
      "1 Gallon"
    ],
    "product_type": "lawn_care",
    "active": true,
    "description": "High-quality growing medium crafted for optimal plant health and root development."
  },
  {
    "asin": "B0DDCPZY3C",
    "title": "Enhanced Living Compost",
    "full_title": "Nature's Way Soil Enhanced Living Compost \u2013 with Fermented Duckweed Extract, 20% Worm Castings, 20% Activated BioChar, 60% Weed-Free Compost \u2013 Organic Garden Soil Amendment for Root & Plant Growth",
    "price": 29.99,
    "category": "Soil & Growing Media",
    "features": [
      "Organic",
      "Worm Castings",
      "BioChar"
    ],
    "product_type": "compost",
    "active": true,
    "description": "High-quality growing medium crafted for optimal plant health and root development."
  },
  {
    "asin": "B0F4NQNTSW",
    "title": "Nature\u2019s Way Soil Spray Pattern Indicator",
    "full_title": "Nature\u2019s Way Soil Spray Pattern Indicator",
    "price": 29.99,
    "category": "Soil & Growing Media",
    "features": [],
    "product_type": "general",
    "active": true,
    "description": "High-quality growing medium crafted for optimal plant health and root development."
  },
  {
    "asin": "B0F9V4HQNK",
    "title": "Liquid Humic & Fulvic Acid with Organic Kelp, Concentrate, Natural Soil Conditio...",
    "full_title": "Nature's Way Soil Liquid Humic & Fulvic Acid with Organic Kelp, Concentrate, Natural Soil Conditioner, Plant Growth Stimulator, 1 Gallon",
    "price": 39.99,
    "category": "Soil & Growing Media",
    "features": [
      "Organic",
      "Concentrate",
      "Liquid",
      "1 Gallon"
    ],
    "product_type": "seaweed_fertilizer",
    "active": true,
    "description": "Natural seaweed extract that provides trace minerals and growth hormones for enhanced plant vigor."
  },
  {
    "asin": "B0FMQNT193",
    "title": "\" Pet",
    "full_title": "Nature's Way Soil\" Pet-Safe Kennel Cleaner & Deodorizer \u2013 Bio-Enzymatic, Non-Toxic, Odor Eliminator for Dog Kennels, Cages, Floors & Bedding \u2013 Professional Strength, Eco-Friendly, 1 Gallon",
    "price": 54.99,
    "category": "Soil & Growing Media",
    "features": [
      "Pet-Safe",
      "1 Gallon"
    ],
    "product_type": "general",
    "active": true,
    "description": "High-quality growing medium crafted for optimal plant health and root development."
  },
  {
    "asin": "B0FG38YYJ5",
    "title": "Nature\u2019s Way Soil Dog Urine Neutral & Lawn",
    "full_title": "Nature\u2019s Way Soil Dog Urine Neutral & Lawn \u2013 1 Gallon | Pet-Safe Grass Repair Spray for Yellow Spots | Odor Eliminator & Soil Reviver for Healthy Green Lawns (1 Gallon)",
    "price": 59.99,
    "category": "Soil & Growing Media",
    "features": [
      "Pet-Safe",
      "1 Gallon"
    ],
    "product_type": "lawn_care",
    "active": true,
    "description": "High-quality growing medium crafted for optimal plant health and root development."
  },
  {
    "asin": "B0F9V3K9L7",
    "title": "Liquid Humic & Fulvic Acid with Organic Kelp, Concentrate,Natural Soil Condition...",
    "full_title": "Nature's Way Soil Liquid Humic & Fulvic Acid with Organic Kelp, Concentrate,Natural Soil Conditioner, Plant Growth Stimulator, 2.5 Gallon (2.5 Gallon)",
    "price": 69.99,
    "category": "Soil & Growing Media",
    "features": [
      "Organic",
      "Concentrate",
      "Liquid",
      "2.5 Gallon"
    ],
    "product_type": "seaweed_fertilizer",
    "active": true,
    "description": "Natural seaweed extract that provides trace minerals and growth hormones for enhanced plant vigor."
  },
  {
    "asin": "B0FF98QKY7",
    "title": "Nature\u2019s Way Soil\u00ae Liquid Biochar with Kelp, Humic & Fulvic Acid",
    "full_title": "Nature\u2019s Way Soil\u00ae Liquid Biochar with Kelp, Humic & Fulvic Acid \u2013 Organic Soil Conditioner for Plants, Gardens & Lawns \u2013 Boost Microbes & Nutrient Retention \u2013 1 Gallon",
    "price": 89.99,
    "category": "Soil & Growing Media",
    "features": [
      "Organic",
      "Liquid",
      "BioChar",
      "1 Gallon"
    ],
    "product_type": "seaweed_fertilizer",
    "active": true,
    "description": "Natural seaweed extract that provides trace minerals and growth hormones for enhanced plant vigor."
  }
];

// Export for different environments
if (typeof module !== 'undefined' && module.exports) {
    module.exports = { products };
} else if (typeof window !== 'undefined') {
    window.productsData = products;
}

// API functions
function getAllProducts() {
    return products;
}

function getProductsByCategory(category) {
    if (category === 'all') return products;
    return products.filter(p => p.category === category);
}

function getProductByAsin(asin) {
    return products.find(p => p.asin === asin);
}

function searchProducts(query) {
    const searchTerm = query.toLowerCase();
    return products.filter(p => 
        p.title.toLowerCase().includes(searchTerm) ||
        p.category.toLowerCase().includes(searchTerm) ||
        p.features.some(f => f.toLowerCase().includes(searchTerm))
    );
}

// Export functions
if (typeof module !== 'undefined' && module.exports) {
    module.exports = {
        products,
        getAllProducts,
        getProductsByCategory,
        getProductByAsin,
        searchProducts
    };
}
